### PR TITLE
add environment checks, correct preprocess_covid19_table

### PR DESCRIPTION
**Pull request by jhgoebbert**
new cell: takes "requirements.txt" and checks if all is satisfied

### CODE REVIEW

**Comment by jhgoebbert** [comment]
download link for CVS data  
https://opendata.arcgis.com/datasets/dd4580c810204019a7b8eb3e0b329dd6_0.csv  
has different date-format for "Meldedatum"

**Comment by jhgoebbert** [comment]
the default regex and dayformat of preprocess_covid19_table.py does not change, but it can be overwritten by arguments

**Review by pnieters — APPROVED** [review]
Should work just fine -- thanks

**Comment by jhgoebbert** [comment]
Thanks!

**Pull request merged**
